services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/mongodb/data

volumes:
  pgdata:      
  mongodata:  
